services:
  lb:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - shared-sockets:/tmp
    depends_on:
      - api1
      - api2
    networks:
      - rinha_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30M"

  api1:
    image: seu-usuario-dockerhub/api-rinha:latest
    platform: linux/amd64
    environment:
      - SOCKET_PATH=/tmp/api1.sock
    volumes:
      - shared-sockets:/tmp
    networks:
      - rinha_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    image: seu-usuario-dockerhub/api-rinha:latest
    platform: linux/amd64
    environment:
      - SOCKET_PATH=/tmp/api2.sock
    volumes:
      - shared-sockets:/tmp
    networks:
      - rinha_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

networks:
  rinha_network:
    driver: bridge

volumes:
  shared-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m