api1:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    environment:
      - SOCKET_PATH=/tmp/api1.sock
    volumes:
      - shared-sockets:/tmp
    networks:
      - rinha_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "350M"

api2:
  build: 
    context: .
    dockerfile: Dockerfile.dev
  platform: linux/amd64
  environment:
    - SOCKET_PATH=/tmp/api2.sock
  volumes:
    - shared-sockets:/tmp
  networks:
    - rinha_network
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  deploy:
    resources:
      limits:
        cpus: "0.6"
        memory: "350M"