FROM --platform=linux/amd64 gradle:8.7-jdk21 AS builder
WORKDIR /app
COPY build.gradle.kts settings.gradle.kts* ./
COPY src ./src
RUN --mount=type=cache,target=/home/gradle/.gradle gradle installDist --no-daemon
RUN mv build/install/* /app/dist

FROM --platform=linux/amd64 eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/dist/lib /app/lib
COPY resources/index.bin /app/resources/index.bin
COPY resources/mcc_risk.json /app/resources/mcc_risk.json
CMD java -XX:+UseSerialGC -XX:-UsePerfData -cp "/app/lib/*" rinha.ServerKt